name = "BabanPack"
author = "Mofo"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2439f401ed4195eafb7bfb2c35e98fd57a74de757fa90e4802eb2dc825d09b7d"

[versions]
forge = "40.1.51"
minecraft = "1.18.2"
