name = "BabanPack"
author = "Mofo"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f204f12b448dc32023532afbb420b6e2b802baa9557f87d8c57f450d9f2cfa16"

[versions]
forge = "40.1.51"
minecraft = "1.18.2"
