name = "BabanPack"
author = "Mofo"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02dada12a95df31b0a42441254d2b9a85a356ab0028ab5d6ebe259c9c659631f"

[versions]
forge = "40.1.51"
minecraft = "1.18.2"
