name = "BabanPack"
author = "Mofo"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acbe721253b2ac4eafe71740eaf6356d325ab2a467bb3a67d0747bb38cce2ab8"

[versions]
forge = "40.1.31"
minecraft = "1.18.2"
