name = "BabanPack"
author = "Mofo"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea7c1bec6a3a798a8899a9de9fc5de9f2fb552739a12eb1e7d2d5d50885aa660"

[versions]
forge = "40.1.51"
minecraft = "1.18.2"
