name = "BabanPack"
author = "Mofo"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db50ccb8de2ed4446203a44d9c91cffc655f38d5088b7328dce33cd333fe19e4"

[versions]
forge = "40.1.51"
minecraft = "1.18.2"
