name = "BabanPack"
author = "Mofo"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c038776d8f5c5acee28c91c16f326e87b8a80a5aded2e90dd4b785c8dffa9671"

[versions]
forge = "40.1.31"
minecraft = "1.18.2"
